#ifndef SYNEEG_STATUS_H
#define SYNEEG_STATUS_H

typedef enum {
    SYNEEG_OK = 0,
    SYNEEG_ERROR_ARGUMENT,
    SYNEEG_ERROR_IO,
    SYNEEG_ERROR_STATE,
    SYNEEG_ERROR_DEVICE_ID,
    SYNEEG_ERROR_VERIFY,
    SYNEEG_ERROR_CAPACITY,
    SYNEEG_ERROR_FORMAT,
    SYNEEG_ERROR_AUTHORITY,
    SYNEEG_ERROR_ADDRESS,
    SYNEEG_ERROR_STALE
} syneeg_status_t;

#endif
